[package]
name = "web"
version = "0.1.0"
authors = ["optifat <pavsmel@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-files = "0.5.0"
tera = "1.5.0"
serde = "1.0"
